name: CTGov Ingestion Pipeline

on:
  workflow_dispatch:   # allow manual run from GitHub UI
  schedule:
    # Every 2 hours on the first Monday of each month
    - cron: "0 */2 * * 1"

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      # Inject from GitHub secrets
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ingestion/requirements.txt
          pip install dbt-snowflake

      - name: Run ingestion
        run: python ingestion/clinical_trials_api.py

      - name: Run dbt models
        run: |
          cd dbt
          dbt run --profiles-dir .