name: CTGov Ingestion Pipeline

on:
  workflow_dispatch: {}   # manual button in Actions

jobs:
  run-ingestion-and-dbt:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # Snowflake (from repo secrets)
      SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE:      SYSADMIN
      SNOWFLAKE_DATABASE:  CLINICAL_TRIALS_DEV
      SNOWFLAKE_WAREHOUSE: TRANSFORM_WH
      SNOWFLAKE_SCHEMA:    RAW                  # used by the Python ingestor
      SNOWFLAKE_STAGING_SCHEMA: STAGING         # used by dbt

      # Ingestion knobs (feel free to tweak for a quick demo)
      SINK:                snowflake
      CTGOV_PAGE_SIZE:     "50"
      CTGOV_MAX_PAGES:     "1"    # 1 page for fast demo
      CTGOV_MAX_RECORDS:   "0"
      CTGOV_START_DATE:    "2015-01-01"
      CTGOV_END_DATE:      "MAX"
      LOG_LEVEL:           "INFO"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ingestion deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ingestion/requirements.txt

      - name: Run ingestion (RAW layer)
        run: |
          echo "Connecting to Snowflake account: $SNOWFLAKE_ACCOUNT"
          python -u ingestion/clinical_trials_api.py

      - name: Install dbt
        run: |
          pip install "dbt-core==1.8.9" "dbt-snowflake==1.8.4"

      - name: dbt debug (optional but helpful)
        working-directory: dbt
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/dbt
        run: dbt debug --target prod --no-write-json

      - name: Run dbt build (STAGING + MARTS + tests)
        working-directory: dbt
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/dbt
        run: dbt build --target prod --no-write-json