name: CTGov Ingestion Pipeline

on:
  # Manual trigger
  workflow_dispatch:
  # Scheduled trigger (first Monday of every month, every 2 hours UTC)
  schedule:
    - cron: "0 */2 ? * MON#1 *"

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r ingestion/requirements.txt
          pip install dbt-snowflake

      - name: Run ingestion script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: CLINICAL_TRIALS_DEV
          SNOWFLAKE_SCHEMA: RAW
          SNOWFLAKE_WAREHOUSE: TRANSFORM_WH
          SNOWFLAKE_ROLE: SYSADMIN
          SINK: snowflake
        run: |
          source venv/bin/activate
          python ingestion/clinical_trials_api.py

      - name: Run dbt models
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/dbt
        run: |
          source venv/bin/activate
          cd dbt
          dbt deps
          dbt run
          dbt test