name: CTGov Ingestion Pipeline

on:
  workflow_dispatch:   # 👈 allows manual run button in Actions tab
  schedule:            # 👈 optional, auto-run every 2 hours on Mondays (UTC)
    - cron: "0 */2 * * 1"

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd ingestion
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingestion script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: CLINICAL_TRIALS_DEV
          SNOWFLAKE_SCHEMA: RAW
          SNOWFLAKE_WAREHOUSE: TRANSFORM_WH
        run: |
          cd ingestion
          python clinical_trials_api.py